# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis
  url: redis://:4ae20ff8ff9c55b78b0998edba153e72cb5a278aa1538fb08b364bd0886963a4@dokku-redis-gambit-redis:6379/1

development:
  adapter: redis
  url: redis://localhost:6379/1

staging:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: redis
  url: redis://localhost:6379/1